config/routes.rb
Rails.application.routes.draw do
  get    '/join',                    to: redirect('/auth/github')
  delete '/logout',                  to: 'sessions#destroy'
  get    '/auth/:provider/callback', to: 'sessions#create'
  get    '/auth/failure',            to: 'sessions#failure'

  localized do
    resources :events,       only: [:index, :show]
    resources :certificates, only: :show
    resource :profile,       only: [:show, :update, :edit]
  end

  namespace :admin do
    resources :users, only: :index do
      resource :accesses, only: [:create, :destroy]
    end

    resources :events, except: :show
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  validates :user,  presence: true
  validates :event, presence: true

  belongs_to :user
  belongs_to :event

  delegate :name, :local, :occurred_at, :organizer, :duration,
           to: :event, prefix: true
  delegate :name, to: :user, prefix: :participant

  def cover_url
    event.certificate_cover_url
  end
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId

  friendly_id :name, use: :slugged

  mount_uploader :certificate_cover, CertificateCoverUploader

  validates :name,        presence: true, uniqueness: true
  validates :slug,        presence: true, uniqueness: true
  validates :summary,     presence: true
  validates :description, presence: true
  validates :occurred_at, presence: true
  validates :local,       presence: true
  validates :address,     presence: true

  scope :not_happened, lambda {
    where('occurred_at > ?', Time.current.yesterday).order(occurred_at: :asc)
  }
end

app/models/user.rb
class User < ApplicationRecord
  validates :provider, presence: true, inclusion: { in: %w(github) }
  validates :uid,      presence: true, uniqueness: { scope: :provider }
  validates :name,     presence: true
  validates :email,    presence: true
  validates :nickname, presence: true
  validates :image,    presence: true

  has_many :certificates

  scope :admin,  -> { where(admin: true) }
  scope :normal, -> { where(admin: false) }
end

app/controllers/admin/accesses_controller.rb
module Admin
  class AccessesController < ApplicationController
    before_action :authenticate_admin!

    def create
      @user = User.normal.find(params[:user_id])
      @user.update admin: true

      redirect_to admin_users_path
    end

    def destroy
      @user = User.admin.find(params[:user_id])
      @user.update admin: false

      redirect_to admin_users_path
    end
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_event, only: [:edit, :update, :destroy]

    def index
      @events = Event.order(occurred_at: :asc)

      respond_to do |format|
        format.html
      end
    end

    def new
      @event = Event.new

      respond_to do |format|
        format.html
      end
    end

    def create
      @event = Event.new event_params

      respond_to do |format|
        if @event.save
          format.html { redirect_to admin_events_path }
        else
          format.html { render :new }
        end
      end
    end

    def edit
      respond_to do |format|
        format.html
      end
    end

    def update
      respond_to do |format|
        if @event.update(event_params)
          format.html { redirect_to admin_events_path }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @event.destroy
      respond_to do |format|
        format.html { redirect_to admin_events_path }
      end
    end

    private

    def set_event
      @event = Event.friendly.find(params[:id])
    end

    def event_params
      params.require(:event)
            .permit(:name, :local, :address, :occurred_at, :summary, :duration,
                    :description, :organizer, :certificate_cover)
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :authenticate_admin!

    def index
      @admins = User.admin
      @users  = User.normal
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :admin_signed_in?
  helper_method :authenticate_admin!
  helper_method :title

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def admin_signed_in?
    user_signed_in? && current_user.admin?
  end

  def authenticate_admin!
    redirect_to :root unless admin_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user!
    redirect_to :root unless user_signed_in?
  end

  def title
    title = @title || t('.title', options)

    "#{title} - #{t('layouts.application.title_suffix')}"
  end

  def options
    record.present? ? { name: record.name } : {}
  end

  def record
    instance_variable_get("@#{controller_name.singularize}".to_sym)
  end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  def show
    @certificate = Certificate.find(params[:id])

    send_data CertificatePDF.new(@certificate).render,
              filename: "#{@certificate.id}.pdf",
              type: 'application/pdf',
              disposition: 'inline'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order(occurred_at: :desc)
    respond_to do |format|
      format.html { @events = decorate_events }
      format.atom { @markdown_renderer = markdown_renderer }
    end
  end

  def show
    @event = EventDecorator.new(Event.friendly.find(params[:id]), view_context)
    @title = @event.name
  end

  private

  def markdown_renderer
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, strikethrough: true)
  end

  def decorate_events
    @events.map { |e| EventDecorator.new(e, view_context) }
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def edit; end

  def show; end

  def update
    current_user.update_attributes(profile_params)
  end

  private

  def profile_params
    params.require(:profile).permit(:name)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def edit; end

  def show; end

  def update
    current_user.update_attributes(profile_params)
  end

  private

  def profile_params
    params.require(:profile).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    creator = SessionCreator.new(request.env['omniauth.auth'])
    session[:user_id] = creator.user.id if creator.call

    redirect_to :root
  end

  def destroy
    reset_session

    redirect_to :root
  end

  def failure
    redirect_to :root
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # TODO: Many '@', improvement is need
    @members = User.order(:name)
    event = Event.not_happened.first

    @next_event = EventDecorator.new(event, view_context) if event
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/member_helper.rb
module MemberHelper
  def image_tag_for(member, github_link: false)
    options =
      if github_link
        { link: "https://github.com/#{member.nickname}", target: '_blank' }
      else
        { link: '#', target: nil }
      end

    content_to_link_by(member, options)
  end

  private

  def content_to_link_by(member, options)
    link_to options[:link],
            target: options[:target], title: member.name, class: 'member',
            style: "background-image: url(#{member.image})" do

      content_tag(:p, member.name, class: :name)
    end
  end
end

app/views/admin/events/_form.html.slim
= simple_form_for([:admin, @event]) do |f|
  = f.input :name
  = f.input :local
  = f.input :address
  = f.input :occurred_at, as: :string, input_html: { value: @event.occurred_at.in_time_zone('Brasilia').strftime('%d-%m-%Y  %H:%M') }

  = f.label :summary
  div[role='tabpanel']
    ul.nav.nav-tabs[role='tablist']
      li.active[role='presentation']
        a[href='#event_summary_text' aria-controls='event_summary_text' role='tab' data-toggle='tab'] = t('.text')
      li[role='presentation']
        a[href='#event_summary_preview' aria-controls='event-event_summary_preview' role='tab' data-toggle='tab' data-element-from='#event_summary' data-element-to='#event_summary_preview'] = t('.preview')
    .tab-content
      .tab-pane.active[id='event_summary_text']
        = f.input :summary, label: false, input_html: { rows: 5 }
      .tab-pane[id='event_summary_preview'] = t('.loading')

  = f.label :description
  div[role='tabpanel']
    ul.nav.nav-tabs[role='tablist']
      li.active[role='presentation']
        a[href='#event_description_text' aria-controls='event_description_text' role='tab' data-toggle='tab'] = t('.text')
      li[role='presentation']
        a[href='#event_description_preview' aria-controls='event_description_preview' role='tab' data-toggle='tab' data-element-from='#event_description' data-element-to='#event_description_preview'] = t('.preview')
    .tab-content
      .tab-pane.active[id='event_description_text']
        = f.input :description, label: false, input_html: { rows: 15 }
      .tab-pane[id='event_description_preview'] = t('.loading')

  fieldset
    legend = t('.certificate_options')
    = f.input :organizer
    = f.input :duration
    .form-group.integer.optional.event_certificate_cover
      = f.label :certificate_cover
      - if @event.certificate_cover?
        = image_tag(@event.certificate_cover_url)
      = f.hidden_field :certificate_cover_cache
      = f.file_field :certificate_cover

  = f.submit class: "pull-right"
  = link_to t('.back'), admin_events_path, class: 'btn-back pull-left'

app/views/admin/events/edit.html.slim
= content_for :header do
  .container
    .page-header
      h1 = t '.title', name: @event.name
      small = t '.subtitle'

.container
  = render 'form'

app/views/admin/events/index.html.slim
= content_for :header do
  .container
    .page-header
      .pull-left
        h1 = t '.title'
        p = t '.subtitle'
      = link_to new_admin_event_path, class: 'btn-add btn-ghost btn-small pull-right' do
        = fa_icon 'plus', text: t('.new')
.container
  table.table.table-striped.table-hover
    thead
      tr
        th = t '.name'
        th = t '.local'
        th = t '.address'
        th = t '.occurred_at'
        th
    tbody
      - @events.each do |event|
        tr
          td = event.name
          td = event.local
          td = event.address
          td = event.occurred_at
          td
            = link_to edit_admin_event_path(event), title: t('.edit'), class: 'btn-edit btn-small' do
              = fa_icon 'pencil-square-o'
            '
            = link_to [:admin, event], method: :delete, title: t('.delete'), class: 'btn-delete btn-small', data: { confirm: t('.delete-confirm') } do
              = fa_icon 'trash'

app/views/admin/events/new.html.slim
= content_for :header do
  .container
    .page-header
      h1 = t '.title'
      small = t '.subtitle'

.container
  = render 'form'

app/views/admin/users/index.html.slim
= content_for :header
  .container
    .page-header
      h1 = t '.title'
      small = t '.subtitle'

.container
  ul.members-grid.border-bottom
    - for admin in @admins do
      li.member
        = image_tag admin.image
        p.name
          = admin.name
          = link_to admin_user_accesses_path(admin), method: :delete, title: t('.revoke'), class: 'btn-revoke'
            = fa_icon 'thumbs-down'

  ul.members-grid
    - for user in @users do
      li.member
        = image_tag user.image
        p.name
          = user.name
          = link_to admin_user_accesses_path(user), method: :post, title: t('.grant'), class: 'btn-grant'
            = fa_icon 'thumbs-up'

app/views/events/_add_to_calendar.html.slim
span.addtocalendar.atc-style-button-icon
  a.atcb-link = fa_icon 'calendar', text: t('.link')
  var.atc_event
    var.atc_date_start = calendar.date_start
    var.atc_date_end = calendar.date_end
    var.atc_timezone = calendar.timezone
    var.atc_title = calendar.title
    var.atc_description = calendar.description
    var.atc_location = calendar.location
    var.atc_organizer = calendar.organizer
    var.atc_organizer_email = calendar.organizer_email

app/views/events/_banner.html.slim
/! events/banner
section.event-banner
  .page-header
    h1.text-center
      = event.name
      small
        ul.list-inline
          li.occurred = event.occurred_at
          li.local = event.local_link

  .summary
    = event.summary

  = event.details_link
/! events/banner

app/views/events/index.html.slim
= content_for :header do
  .container
    .page-header
      h1
        => t '.title'
        = link_to fa_icon('rss'), events_url(format: 'atom')
      p = t '.subtitle'


section.events
  .container
    - @events.each do |event|
      article.event-item
        header
          h2 = link_to event.name, event
          time = event.occurred_at
        = event.summary

app/views/events/show.html.slim
= content_for :header
  = render 'banner', event: @event

.event.event-show
  .container
    .description
      = @event.description

    p = render 'add_to_calendar', calendar: @event.calendar_properties

    .local-map
      = @event.local_map_link

    .share-buttons
      h4 Compartilhe:
      - @event.share_buttons.each do |media, url|
        = link_to url, target: '_blank', class: media
          = fa_icon media

app/views/layouts/application.html.slim
doctype 5
html lang="#{I18n.locale}"

  head
    title = title

    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'
    meta name='description' content= t('.description')
    meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' http://* 'unsafe-inline'; script-src 'self' http://* 'unsafe-inline' 'unsafe-eval'"

    = auto_discovery_link_tag :atom, events_url(format: 'atom')

    = stylesheet_link_tag :application, media: :all, debug: false, 'data-turbolinks-track' => true
    = csrf_meta_tags
    = javascript_include_tag :application, debug: false, 'data-turbolinks-track' => true

    / [if lt IE 9]
      = javascript_include_tag '//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'
      = javascript_include_tag '//oss.maxcdn.com/respond/1.4.2/respond.min.js'

  body[class="#{controller_name}-#{action_name}"]
    /= render 'shared/fork_me_ribbon'

    = render 'shared/navbar'

    div[class="image-header #{current_page?(:root) ? '' : 'small'}"]
      = yield :header

    = yield

    = render 'shared/footer'

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GURU-PR - Grupo de Usuários Ruby do Paraná" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>


    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>        
        <%= link_to "GURU-PR - Grupo de Usuários Ruby do Paraná", root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "#" do %>
                  <%= fa_icon "github", text: "Join with Github" %>
                <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-6">					
          <%= image_tag 'ruby_symbal.png'%>
        </div>
        <div class="col-lg-6">
          <%= yield %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <%= render 'welcome/members' %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/profiles/_certificate.html.slim
- cache certificate do
  = link_to certificate_url(certificate), class: 'card-certificate', style: "background-image: url(#{certificate.cover_url})", target: '_blank', title: certificate.event.name do
    p
      button.btn-add.btn-small type="button"
        = fa_icon 'download fw', text: 'Download'

app/views/profiles/_fields.html.slim
#profile_fields
  .member-page.profile-image
    = image_tag_for(current_user)

  .container
    .line
      = fa_icon 'user-o fw'
      = current_user.name

    .line
      = fa_icon 'envelope-o fw'
      = truncate current_user.email, length: 28

    .line
      = fa_icon 'github fw'
      = current_user.nickname

  .line-button.text-center.btn-block
    = link_to t('.edit'), edit_profile_url, remote: true, class: 'btn-add btn-small btn-block'

app/views/profiles/_form.html.slim
.profile-form
  = simple_form_for current_user, as: :profile, url: profile_path, remote: true do |f|
    .member-page.profile-image
      = image_tag_for(current_user)

    - if admin_signed_in?
      p.admin-text.text-center
        = fa_icon 'lock', text: t('.admin')

    = f.input :name, required: true

    .line-button.text-center
      = f.submit t('.save'), class: 'btn-add btn-small btn-block'

app/views/profiles/edit.js.erb
$('#profile_fields').remove();

var $form = "<%= j render 'form' %>";

$('.centered-card-profile').append($form);

app/views/profiles/show.html.slim
= content_for :header do
  .container
    .page-header
      h1 = t('.title')
      small = t('.subtitle')

.centered-card-profile
  = render 'fields'

section.certificates
  h3 = t('.certificates_title')

  .container
    .certificates-grid
      = render(partial: 'certificate', collection: current_user.certificates, cached: true) || t('.no_certificates_html')

app/views/profiles/update.js.erb
$('#edit_profile').remove();

var $fields = "<%= j render 'fields' %>";

$('.centered-card-profile').append($fields);

app/views/shared/_admin_nav.html.slim
li.admin-nav.dropdown
  a.dropdown-toggle[href="#" data-toggle="dropdown"]
    = fa_icon 'lock', text: raw("#{t('.admin')} #{fa_icon('caret-down')}")
  ul.dropdown-menu
    li = link_to admin_users_path do
      = fa_icon 'user', text: t('.users')
    li = link_to admin_events_path do
      = fa_icon 'calendar', text: t('.events')

app/views/shared/_footer.html.slim
/! shared/footer
footer.site-footer
  .container
    ul.social
      li
        = link_to 'https://github.com/guru-pr', target: '_blank' do
          = fa_icon 'github'
      li
        = link_to 'https://twitter.com/guru_pr/', target: '_blank' do
          = fa_icon 'twitter'
      li
        = link_to 'https://www.facebook.com/groups/704256192948428/', target: '_blank' do
          = fa_icon 'facebook-official'
    p
      small &copy; Grupo de Usuários Ruby do Paraná. Feito com ruby on rails e com <3

/! shared/navbar

app/views/shared/_member_nav.html.slim
li.member-nav.dropdown
  a.dropdown-toggle[href="#" data-toggle="dropdown"]
    = fa_icon 'at', text: raw("#{current_user.nickname} #{fa_icon('caret-down')}")
  ul.dropdown-menu
    li = link_to profile_path do
      = fa_icon 'id-card-o fw', text: t('.profile')
    li = link_to logout_path, method: :delete do
      = fa_icon 'sign-out fw', text: t('.sign_out')

app/views/shared/_members_grid.html.slim
/! shared/members_grid
- cache member do
  = image_tag_for(member, github_link: true)
/! shared/members_grid

app/views/shared/_navbar.html.slim
/! shared/navbar
nav.navbar.navbar-default
  .container
    .navbar-header
      button.navbar-toggle[data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'GURU-PR', root_path, class: 'navbar-brand'

    #navbar.navbar-collapse.collapse
      ul.guru-nav
        li = link_to events_path do
          = fa_icon 'calendar', text: t('.events')
        - if admin_signed_in?
          = render 'shared/admin_nav'
        - if user_signed_in?
          = render 'shared/member_nav'
        - unless user_signed_in?
          li
            = link_to join_path do
              = fa_icon 'github', text: t('.join')
/! shared/navbar

app/views/welcome/_members.html.erb
<div class="row">
	<div class="col-lg-2">
		<h3>Members <a name="members"></a></h3>
	</div>
</div>

<div class="row">  
<% @members.each do |member|%>
  <div class="col-lg-3">
    <%= link_to "http://github.com/#{member.name}", target: '_blank' do %>
      <%= image_tag "http://placehold.it/100", alt: 'Teste', class: 'member_image' %>
    <% end %>
    <p><%= link_to member.name, "http://github.com/#{member.name}", target: '_blank' %></p>
   </div>
   <% end %>
</div>

app/views/welcome/_tweets.html.slim
section.event-banner.tw-content
  .text-center
    a.twitter-timeline[data-width="800" data-height="280" data-link-color="#cc342d" data-chrome="nofooter noheader noborders transparent" href="https://twitter.com/#{Rails.application.config.twitter_username}"]
    script[async=true src="//platform.twitter.com/widgets.js" charset="utf-8"]

app/views/welcome/index.html.slim
= content_for :header
  - if @next_event
    = render 'events/banner', event: @next_event
  - else
    = render 'tweets'

section.members
  h3
    = t(".members")
    span.badge =< @members.size

  .members-grid
    = render partial: 'shared/members_grid', collection: @members, as: :member, cached: true